BooksManagement/urls.py
from .views import book_list, book_create, book_update, book_delete
from django.urls import path

app_name = 'book'

urlpatterns = [
    path('', book_list, name='book_list'),
    path('create/book/', book_create, name='book_create'),
    path('update/book/<int:pk>/', book_update, name='book_update'),
    path('delete/book/<int:pk>/', book_delete, name='book_delete'),
]

LibraryManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BooksManagement.urls'))
]

BooksManagement/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    name = models.CharField(max_length=100)
    family = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} {self.family}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"


class Book(models.Model):
    title = models.CharField(max_length=100)
    isbn = models.CharField(max_length=17)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    summary = models.TextField()
    category = models.ManyToManyField(Category, related_name='category')
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.title}"


class BorrowedBook(models.Model):
    user = models.ForeignKey(User, related_name='user_borrowed', on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name='borrowed_book', on_delete=models.CASCADE)
    borrow_date = models.DateTimeField()
    return_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.book.title}"

BooksManagement/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'summary',
                  'isbn', 'author', 'category']

BooksManagement/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book
from .forms import BookForm


def book_list(request):
    books = Book.objects.all()

    context = {
        'books': books
    }
    return render(request, 'BooksManagement/books_list.html', context)


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book:book_list')

    else:
        form = BookForm()
    return render(request, 'BooksManagement/book_create.html', {'form': form})


def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('book:book_list')
    else:
        form = BookForm(instance=book)
    return render(request, 'BooksManagement/book_update.html', {'form': form})


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == "POST":
        book.delete()
        return redirect('book:book_list')
    return render(request, 'BooksManagement/book_delete.html', {'book': book})

BooksManagement/templates/BooksManagement/book_create.html
{% extends 'base.html' %}
{% block title %}add new book to library{% endblock %}

{% block content %}
    <div class="container mt-4">

    <h2>Add Book</h2>
    <form method="post" novalidate="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'book:book_list' %}" class="btn btn-secondary">Cancel</a>
    </form>

</div>
{% endblock %}

BooksManagement/templates/BooksManagement/book_delete.html
{% extends 'base.html' %}

{% block title %}Delete Book{% endblock %}

{% block content %}
<h2>Are you sure you want to delete "{{ book.title }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a href="{% url 'book:book_list'  %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

BooksManagement/templates/BooksManagement/book_update.html
{% extends 'base.html' %}
{% block title %}update the book{% endblock %}
{% block content %}
    <h2>update Book</h2>
    <form method="post" novalidate="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Update</button>
        <a href="{% url 'book:book_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

BooksManagement/templates/BooksManagement/books_list.html
{% extends 'base.html' %}
{% block title %}home of library management{% endblock %}
{% block content %}
    <div class="container mt-4">
        {% for book in books %}
            <div class="container">
                <div class="row">
                    <div class="col-4">
                        <h4>{{ book.title }}</h4>
                        <p><strong>Author:</strong> {{ book.author }}</p>
                        <p><strong>ISBN:</strong> {{ book.isbn }}</p>
                        <p><strong>Summary:</strong> {{ book.summary }}</p>
                        <p><strong>Categories:</strong>
                    </div>
                    <div class="col-4">
                        {% for cat in book.category.all %}
                            <p>{{ cat.name }}</p>
                        {% endfor %}

                    </div>
                    <div class="col-4">
                        <a href="{% url 'book:book_update' book.id %}" class="btn btn-warning">Edit</a>
                        <a type="submit" href="{% url 'book:book_delete' book.id %}" class="btn btn-danger">Delete</a>
                        {% if book.is_available %}
                            <a href="#" class="btn btn-primary">Borrow</a>
                        {% else %}
                            <a href="" class="btn btn-secondary">not available</a>
                        {% endif %}

                    </div>
                </div>
            </div>
            <hr>
        {% endfor %}

    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'book:book_list' %}">Library</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book:book_list' %}">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book:book_create' %}">Add Book</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">List of borrowed books</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>